/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpeditionRouteImport } from './routes/expedition'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as LoginRoleRouteImport } from './routes/login.$role'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedLivreurRouteImport } from './routes/_authenticated/livreur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedManagerAccountingRouteImport } from './routes/_authenticated/manager.accounting'
import { Route as AuthenticatedAdminWholesaleRouteImport } from './routes/_authenticated/admin.wholesale'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin.stock'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPosRouteImport } from './routes/_authenticated/admin.pos'
import { Route as AuthenticatedAdminLogisticsRouteImport } from './routes/_authenticated/admin.logistics'
import { Route as AuthenticatedAdminExpeditionPageRouteImport } from './routes/_authenticated/admin.expedition-page'
import { Route as AuthenticatedAdminContactPageRouteImport } from './routes/_authenticated/admin.contact-page'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionRoute = ExpeditionRouteImport.update({
  id: '/expedition',
  path: '/expedition',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => LoginRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurRoute = AuthenticatedLivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedManagerAccountingRoute =
  AuthenticatedManagerAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedAdminWholesaleRoute =
  AuthenticatedAdminWholesaleRouteImport.update({
    id: '/wholesale',
    path: '/wholesale',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPosRoute = AuthenticatedAdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLogisticsRoute =
  AuthenticatedAdminLogisticsRouteImport.update({
    id: '/logistics',
    path: '/logistics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpeditionPageRoute =
  AuthenticatedAdminExpeditionPageRouteImport.update({
    id: '/expedition-page',
    path: '/expedition-page',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactPageRoute =
  AuthenticatedAdminContactPageRouteImport.update({
    id: '/contact-page',
    path: '/contact-page',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/expedition': typeof ExpeditionRoute
  '/login': typeof LoginRouteWithChildren
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/livreur': typeof AuthenticatedLivreurRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/pos': typeof AuthenticatedPosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/contact-page': typeof AuthenticatedAdminContactPageRoute
  '/admin/expedition-page': typeof AuthenticatedAdminExpeditionPageRoute
  '/admin/logistics': typeof AuthenticatedAdminLogisticsRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/manager/accounting': typeof AuthenticatedManagerAccountingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/expedition': typeof ExpeditionRoute
  '/login': typeof LoginRouteWithChildren
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/pos': typeof AuthenticatedPosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/contact-page': typeof AuthenticatedAdminContactPageRoute
  '/admin/expedition-page': typeof AuthenticatedAdminExpeditionPageRoute
  '/admin/logistics': typeof AuthenticatedAdminLogisticsRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/manager/accounting': typeof AuthenticatedManagerAccountingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/expedition': typeof ExpeditionRoute
  '/login': typeof LoginRouteWithChildren
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/livreur': typeof AuthenticatedLivreurRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/contact-page': typeof AuthenticatedAdminContactPageRoute
  '/_authenticated/admin/expedition-page': typeof AuthenticatedAdminExpeditionPageRoute
  '/_authenticated/admin/logistics': typeof AuthenticatedAdminLogisticsRoute
  '/_authenticated/admin/pos': typeof AuthenticatedAdminPosRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/_authenticated/manager/accounting': typeof AuthenticatedManagerAccountingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/expedition'
    | '/login'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/livreur'
    | '/manager'
    | '/pos'
    | '/article/$slug'
    | '/login/$role'
    | '/product/$slug'
    | '/admin/blog'
    | '/admin/contact-page'
    | '/admin/expedition-page'
    | '/admin/logistics'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/users'
    | '/admin/wholesale'
    | '/manager/accounting'
    | '/admin/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/expedition'
    | '/login'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/livreur'
    | '/pos'
    | '/article/$slug'
    | '/login/$role'
    | '/product/$slug'
    | '/admin/blog'
    | '/admin/contact-page'
    | '/admin/expedition-page'
    | '/admin/logistics'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/users'
    | '/admin/wholesale'
    | '/manager/accounting'
    | '/admin'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/expedition'
    | '/login'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/livreur'
    | '/_authenticated/manager'
    | '/_authenticated/pos'
    | '/article/$slug'
    | '/login/$role'
    | '/product/$slug'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/contact-page'
    | '/_authenticated/admin/expedition-page'
    | '/_authenticated/admin/logistics'
    | '/_authenticated/admin/pos'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/wholesale'
    | '/_authenticated/manager/accounting'
    | '/_authenticated/admin/'
    | '/_authenticated/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ExpeditionRoute: typeof ExpeditionRoute
  LoginRoute: typeof LoginRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedition': {
      id: '/expedition'
      path: '/expedition'
      fullPath: '/expedition'
      preLoaderRoute: typeof ExpeditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof LoginRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/manager/accounting': {
      id: '/_authenticated/manager/accounting'
      path: '/accounting'
      fullPath: '/manager/accounting'
      preLoaderRoute: typeof AuthenticatedManagerAccountingRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/admin/wholesale': {
      id: '/_authenticated/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AuthenticatedAdminWholesaleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pos': {
      id: '/_authenticated/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AuthenticatedAdminPosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logistics': {
      id: '/_authenticated/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AuthenticatedAdminLogisticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expedition-page': {
      id: '/_authenticated/admin/expedition-page'
      path: '/expedition-page'
      fullPath: '/admin/expedition-page'
      preLoaderRoute: typeof AuthenticatedAdminExpeditionPageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact-page': {
      id: '/_authenticated/admin/contact-page'
      path: '/contact-page'
      fullPath: '/admin/contact-page'
      preLoaderRoute: typeof AuthenticatedAdminContactPageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminContactPageRoute: typeof AuthenticatedAdminContactPageRoute
  AuthenticatedAdminExpeditionPageRoute: typeof AuthenticatedAdminExpeditionPageRoute
  AuthenticatedAdminLogisticsRoute: typeof AuthenticatedAdminLogisticsRoute
  AuthenticatedAdminPosRoute: typeof AuthenticatedAdminPosRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWholesaleRoute: typeof AuthenticatedAdminWholesaleRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminContactPageRoute: AuthenticatedAdminContactPageRoute,
  AuthenticatedAdminExpeditionPageRoute: AuthenticatedAdminExpeditionPageRoute,
  AuthenticatedAdminLogisticsRoute: AuthenticatedAdminLogisticsRoute,
  AuthenticatedAdminPosRoute: AuthenticatedAdminPosRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWholesaleRoute: AuthenticatedAdminWholesaleRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerAccountingRoute: typeof AuthenticatedManagerAccountingRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerAccountingRoute: AuthenticatedManagerAccountingRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLivreurRoute: typeof AuthenticatedLivreurRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLivreurRoute: AuthenticatedLivreurRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LoginRouteChildren {
  LoginRoleRoute: typeof LoginRoleRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginRoleRoute: LoginRoleRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ExpeditionRoute: ExpeditionRoute,
  LoginRoute: LoginRouteWithChildren,
  ProductsRoute: ProductsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
