/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as LoginRoleRouteImport } from './routes/login.$role'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedLivreurRouteImport } from './routes/_authenticated/livreur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin.stock'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPosRouteImport } from './routes/_authenticated/admin.pos'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/login/$role',
  path: '/login/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurRoute = AuthenticatedLivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPosRoute = AuthenticatedAdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/livreur': typeof AuthenticatedLivreurRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/livreur': typeof AuthenticatedLivreurRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/livreur': typeof AuthenticatedLivreurRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/login/$role': typeof LoginRoleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/pos': typeof AuthenticatedAdminPosRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/livreur'
    | '/manager'
    | '/login/$role'
    | '/product/$slug'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/account'
    | '/livreur'
    | '/manager'
    | '/login/$role'
    | '/product/$slug'
    | '/admin/pos'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/products'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/livreur'
    | '/_authenticated/manager'
    | '/login/$role'
    | '/product/$slug'
    | '/_authenticated/admin/pos'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LoginRoleRoute: typeof LoginRoleRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/login/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pos': {
      id: '/_authenticated/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AuthenticatedAdminPosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPosRoute: typeof AuthenticatedAdminPosRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPosRoute: AuthenticatedAdminPosRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLivreurRoute: typeof AuthenticatedLivreurRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLivreurRoute: AuthenticatedLivreurRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LoginRoleRoute: LoginRoleRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
